name: Alpha Lint

on:
  workflow_call:

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório que está sendo testado
      - name: Checkout Target Repo
        uses: actions/checkout@v4

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Instala ferramentas de lint isoladas
      - name: Install Lint Tooling
        run: |
          npm install \
            eslint \
            @eslint/js \
            typescript-eslint \
            eslint-config-prettier \
            prettier

      # ESLint usando config central do DevSecOps
      - name: Run ESLint
        run: |
          npx eslint . \
            --config ./lint/eslint.config.mjs \
            --no-eslintrc \
            --ext .js,.ts,.tsx

      # Prettier check
      - name: Prettier Check
        run: |
          npx prettier . \
            --config ./lint/.prettierrc \
            --check