name: Alpha Lint

on:
  workflow_call:

  pull_request:
    branches:
      - main


permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Repo que está sendo testado
      - name: Checkout Target Repo
        uses: actions/checkout@v4

      # Repo DevSecOps com as configs
      - name: Checkout DevSecOps Config
        uses: actions/checkout@v4
        with:
          repository: ORG/DevSecOps
          path: devsecops

      # Setup node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Instala ESLint isolado
      - name: Install ESLint
        run: |
          npm install \
          eslint \
          @eslint/js \
          typescript-eslint \
          eslint-config-prettier \
          prettier

      # Run lint usando config central
      - name: Run ESLint
        run: |
          npx eslint . \
            --config devsecops/lint-config/eslint.config.mjs \
            --ext .js,.ts,.tsx

      # Prettier check
      - name: Prettier Check
        run: |
          npx prettier . \
            --config devsecops/lint/.prettierrc \
            --check